name: Deploy Vue App test-deploy to GitHub Pages
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest@latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            cd /root/web_demo
            ls -al
            rm -rf test-deploy
            # git clone git@github.com:songchunfan/test-deploy.git -b ${{ github.ref_name }}
            # cd test-deploy
            # npm install
            # npm run build
