name: Deploy Vue App test-deploy to GitHub Pages
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/test-deploy
            git pull
            npm install
            npm run build
